# Generated by Django 5.0.6 on 2024-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_market', '0009_remove_rating_student_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Art', 'Art'), ('Music', 'Music'), ('Computer Science', 'Computer Science'), ('French', 'French'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
