# Generated by Django 5.0.6 on 2024-07-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_market', '0012_tutor_iban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['display_name']},
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='ratings',
        ),
    ]
