# Generated by Django 5.0.6 on 2024-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_market', '0014_alter_rating_tutor_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='calendly_event_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='calendly_personal_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
