# Generated by Django 5.0.6 on 2024-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_market', '0016_alter_tutor_calendly_personal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='calendly_personal_token',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
