# Generated by Django 5.0.6 on 2024-07-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('tutor_market', '0011_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor_market.subject'),
        ),
    ]
