# Generated by Django 5.0.6 on 2024-07-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_tutoringsession_payment_id_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_secret',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
