# Generated by Django 5.0.6 on 2024-08-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_tutoringsession_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringsession',
            name='subject',
        ),
    ]
